import type { ChainId } from "../../utils/types.js";

export default {
  chainNames: {
    arbitrum: "arbitrum-one",
    astar: "astar",
    aurora: "aurora",
    avalanche: "avalanche",
    base: "base",
    binancesmartchain: "binance-smart-chain",
    blast: "blast",
    canto: "canto",
    cardano: "milkomeda-cardano",
    celo: "celo",
    cosmos: "cosmos",
    cronos: "cronos",
    energi: "energi",
    ethereum: "ethereum",
    fantom: "fantom",
    filecoin: "filecoin",
    gnosis: "gnosis",
    harmony: "harmony-shard-0",
    hydra: "hydra",
    kava: "kava",
    linea: "linea",
    mantle: "mantle",
    metis: "metis-andromeda",
    mode: "mode",
    moonbeam: "moonbeam",
    moonriver: "Moonriver",
    near: "near-protocol",
    optimism: "optimistic-ethereum",
    polygon: "polygon-pos",
    solana: "solana",
    sora: "sora",
    syscoin: "syscoin",
    velas: "velas",
    zksync: "zksync",
  },
  geckoIds: {
    1: "eth",
    10: "optimism",
    56: "bsc",
    101: "solana",
    137: "polygon_pos",
    // 250: "ftm",
    324: "zksync",
    8453: "base",
    34443: "mode",
    42161: "arbitrum",
    43114: "avax",
    59144: "linea",
    81457: "blast",
  } as Record<ChainId, string>,
};
