export default {
  chainIds: {
    1: "eth",
    10: "op",
    // 25: "cro",
    56: "bsc",
    // 61: "ETH",
    // 100: "xdai",
    137: "matic",
    250: "ftm",
    324: "era",
    // 1284: "mobm",
    // 1285: "movr",
    // 2222: "kava",
    // 5000: "MNT",
    // 7700: "canto",
    8453: "base",
    34443: "mode",
    42161: "arb",
    // 42220: "celo",
    43114: "avax",
    59144: "linea",
    81457: "blast",
  },
  protocols: {
    aave3: "aave",
    balancer2: "balancer",
    compound3: "compound",
    camelot2: "camelot",
    gmx2: "gmx",
    lifiprotocol: "lifi",
    lodestar2: "lodestar",
    pancakeswap3: "pancakeswap",
    pendle2: "pendle",
    plutusdao: "plutus",
    squidrouter: "squid",
    swellnetwork: "swell",
    traderjoexyz: "traderjoe",
    uniswap3: "uniswap",
    velodrome2: "velodrome",
  },
  reversed_protocols: {
    aave: "aave3",
    balancer: "balancer2",
    compound: "compound3",
    gmx: "gmx2",
    lifi: "lifiprotocol",
    lodestar: "lodestar2",
    pancakeswap: "pancakeswap3",
    pendle: "pendle2",
    plutus: "plutusdao",
    squid: "squidrouter",
    swell: "swellnetwork",
    traderjoe: "traderjoexyz",
    uniswap: "uniswap3",
    velodrome: "velodrome2",
  },
  pools: {
    "3crv": "3pool",
    crvfrax: "fraxusdc",
    crv3crypto: "pendle2",
    crvfraxusdp: "fraxusdp",
  },
} as Record<string, Record<string | number, string>>;
