export default {
  actions: {
    borrow: [
      "aave",
      "compound",
      // "juice",
      // "lodestar", // "dolomite"
    ],
    bridge: [
      "across",
      "axelar",
      "bungee",
      "debridge",
      "hop",
      "jumper",
      "lifi",
      "orbiter",
      "socket",
      "squid",
      "stargate",
      "synapse",
      "reservoir",
    ],
    // claim: [
    // "aerodrome",
    // "bladeswap",
    // "camelot",
    // "compound",
    // "hop",
    // "lodestar",
    // "stargate",
    // "velodrome",
    // "dolomite",
    // ], // "plutus" execution error
    close: [
      // "gmx",
      "hyperliquid",
    ],
    deposit: [
      "aave",
      // "aerodrome",
      // "ambient",
      // "bladeswap",
      // "camelot",
      "compound",
      // "curve",
      // "gmx",
      "hop",
      // "juice",
      // "eigenlayer",
      // "lodestar",
      // "pendle",
      "rocketpool",
      // "stargate",
      // "synapse",
      // "thruster",
      // "uniswap",
      // "velodrome",
      // "dolomite",
      "hyperliquid",
    ], // "dopex" not supported yet
    lend: [
      "aave",
      "compound",
      // "juice",
      // "lodestar",
      // "dolomite"
    ],
    // lock: [
    // "aerodrome",
    // "bladeswap",
    // "pendle",
    // "plutus",
    // "velodrome",
    // "thena",
    // ],
    long: [
      // "gmx",
      "hyperliquid",
    ],
    repay: [
      "aave",
      "compound",
      // "juice",
      // "lodestar", // "dolomite"
    ],
    short: [
      // "gmx",
      "hyperliquid",
    ],
    stake: [
      // "eigenlayer",
      "etherfi",
      // "gmx",
      "kelpdao",
      "lido",
      // "lodestar",
      // "plutus",
      "rocketpool",
      // "stargate",
      "swell",
      // "dolomite",
      // "ethena",
      // "renzo",
    ], // "hop" execution error
    swap: [
      "aerodrome",
      "ambient",
      "cowswap",
      // "bladeswap",
      "paraswap",
      "sushiswap",
      "uniswap",
      "leetswap",
      "llamazip",
      "curve",
      "camelot",
      "balancer",
      "hashflow",
      "hyperliquid",
      "kyberswap",
      "0x",
      "matcha",
      "1inch",
      "lifi",
      "jumper",
      "odos",
      "openocean",
      "pancakeswap",
      "synapse",
      // "syncswap",
      "thruster",
      "traderjoe",
      "velodrome",
    ],
    transfer: ["hyperliquid"],
    // unlock: [
    // "aerodrome",
    // "bladeswap",
    // "pendle",
    // "plutus",
    // "thena",
    // "velodrome",
    // ],
    unstake: [
      // "eigenlayer",
      "etherfi",
      // "gmx",
      // "lodestar",
      // "plutus",
      "rocketpool",
      // "stargate",
      // "dolomite",
      // "ethena",
    ],
    // vote: [
    //   // "bladeswap"
    // ],
    withdraw: [
      "aave",
      // "aerodrome",
      // "ambient",
      // "bladeswap",
      // "camelot",
      "compound",
      // "curve",
      // "dolomite",
      // "eigenlayer",
      // "gmx",
      "hop",
      // "juice",
      // "lodestar",
      // "pendle",
      "rocketpool",
      // "stargate",
      // "synapse",
      // "thruster",
      // "uniswap",
      // "velodrome",
      "hyperliquid",
    ],
  } as Record<string, string[]>,
  chains: [
    "Arbitrum",
    // "Arbitrum One",
    // "Avalanche",
    "Base",
    // "Binance",
    // "BinanceSmartChain",
    "Blast",
    // "BSC",
    "Ethereum",
    // "Homestead",
    // "Linea",
    // "Linea-Mainnet",
    // "Mainnet",
    // "Matic",
    // "Mode",
    "Optimism",
    // "Polygon",
    // "zkSync",
    "Solana",
  ],
  conditions: {
    condition: [
      "Gas",
      "Balance",
      "Price",
      "Health Factor",
      "LTV (Loan To Value)",
      "Market Cap",
      "FDV (Fully Diluted Value)",
      "Yield (APY)",
      "Funding Rate",
      "Open Interest",
    ],
    time: ["Start Time", "End Time", "Repeat", "Random"],
  },
  protocols: [
    "0x",
    "1inch",
    "Aave",
    "Across",
    "Aerodrome",
    "Ambient",
    "Axelar",
    "Balancer",
    // "Bladeswap",
    "Bungee",
    "Camelot",
    "Compound",
    "Cowswap",
    "Curve",
    "DeBridge",
    // "Dolomite",
    // "Dopex",
    // "EigenLayer",
    "EtherFi",
    // "GMX",
    "Hashflow",
    "Hop",
    // "JonesDAO",
    // "Juice",
    "Jumper",
    // "Kwenta",
    "KelpDAO",
    "Kyberswap",
    "Leetswap",
    "Lido",
    "LiFi",
    "Llamazip",
    // "Lodestar",
    "Matcha",
    "Odos",
    "OpenOcean",
    "Orbiter",
    "PancakeSwap",
    "ParaSwap",
    // "Pendle",
    // "Plutus",
    // "Reservoir",
    "RocketPool",
    // "Rodeo",
    "Slate",
    "Socket",
    "Squid",
    "Stargate",
    "SushiSwap",
    "Swell",
    "Synapse",
    // "SyncSwap",
    // "Thena",
    "Thruster",
    "TraderJoe",
    "Uniswap",
    "Velodrome",
    // "Ethena",
    // "Renzo",
    "Hyperliquid",
  ],
};
