import dotenv from "dotenv";

dotenv.config();

export default {
  1: [
    "https://ethereum-rpc.publicnode.com",
    "https://eth.llamarpc.com",
    "https://eth.drpc.org",
    "https://rpc.public.curie.radiumblock.co/http/ethereum",
    "https://1rpc.io/eth",
  ],
  10: [
    "https://optimism-rpc.publicnode.com",
    "https://optimism.llamarpc.com",
    "https://optimism.drpc.org",
    "https://endpoints.omniatech.io/v1/op/mainnet/public",
    "https://1rpc.io/op",
  ],
  // 25: "https://cronos-evm-rpc.publicnode.com",
  56: [
    "https://bsc-rpc.publicnode.com",
    "https://binance.llamarpc.com",
    "https://bsc.drpc.org",
    "https://endpoints.omniatech.io/v1/bsc/mainnet/public",
    "https://1rpc.io/bnb",
  ],
  // 61: "https://etc.rivet.link",
  // 100: "https://gnosis-rpc.publicnode.com",
  137: [
    "https://polygon-rpc.com",
    "https://polygon-bor-rpc.publicnode.com",
    "https://polygon.llamarpc.com",
    "https://endpoints.omniatech.io/v1/matic/mainnet/public",
    "https://1rpc.io/matic",
  ],
  // 250: "https://fantom-rpc.publicnode.com",
  // 314: "https://rpc.ankr.com/filecoin",
  324: [
    "https://mainnet.era.zksync.io",
    "https://zksync.meowrpc.com",
    "https://1rpc.io/zksync2-era",
    "https://endpoints.omniatech.io/v1/zksync-era/mainnet/public",
    "https://go.getblock.io/f76c09905def4618a34946bf71851542",
  ],
  // 1284: "https://rpc.api.moonbeam.network",
  // 1285: "https://moonriver-rpc.publicnode.com",
  // 2222: "https://kava-evm-rpc.publicnode.com",
  // 5000: "https://rpc.mantle.xyz",
  // 7700: "https://canto.slingshot.finance",
  8453: [
    "https://base-rpc.publicnode.com",
    "https://base.llamarpc.com",
    "https://base.drpc.org",
    "https://base.rpc.subquery.network/public",
    "https://1rpc.io/base",
  ],
  34443: [
    "https://mainnet.mode.network",
    "https://mode.drpc.org",
    "https://1rpc.io/mode",
  ],
  42161: [
    `https://arb-mainnet.g.alchemy.com/v2/${process.env.ALCHEMY_KEY}`,
    `https://arbitrum-mainnet.infura.io/v3/${process.env.INFURA_KEY}`,
    "https://arbitrum-one-rpc.publicnode.com",
    "https://arbitrum-one.public.blastapi.io",
    "https://arbitrum.drpc.org",
    "https://arbitrum.llamarpc.com",
    "https://endpoints.omniatech.io/v1/arbitrum/mainnet/public",
    "https://arbitrum.meowrpc.com",
    "https://arbitrum.rpc.subquery.network/public",
  ],
  // 42220: "https://1rpc.io/celo",
  43114: [
    "https://avalanche-c-chain-rpc.publicnode.com",
    "https://avalanche.public-rpc.com",
    "https://avalanche.blockpi.network/v1/rpc/public",
    "https://endpoints.omniatech.io/v1/avax/mainnet/public",
    "https://rpc.ankr.com/avalanche",
  ],
  59144: [
    "https://rpc.linea.build",
    "https://linea-rpc.publicnode.com",
    "https://linea.drpc.org",
    "https://linea.blockpi.network/v1/rpc/public",
    "https://1rpc.io/linea",
  ],
  81457: [
    `https://blast-mainnet.infura.io/v3/${process.env.INFURA_KEY}`,
    "https://rpc.blast.io",
    "https://blastl2-mainnet.public.blastapi.io",
    "https://blast.din.dev/rpc",
    "https://blast.blockpi.network/v1/rpc/public",
    "https://blast.drpc.org",
  ],
  101: [
    `https://mainnet.helius-rpc.com/?api-key=${process.env.HELIUS_API_KEY}`,
  ],
} as Record<number, string[]>;
