export default {
  1: [
    "USDC",
    "USDT",
    "USDD",
    "SGETH",
    "DAI",
    "FRAX",
    "sUSD",
    "LUSD",
    "MAI",
    "Metis",
    "mETH",
  ],
  56: ["BUSD", "USDT", "USDD", "Metis"],
  43114: ["USDC", "USDT", "FRAX"],
  137: ["USDC", "USDT", "DAI"],
  42161: ["USDC", "USDT", "SGETH", "FRAX"],
  10: ["USDC", "SGETH", "DAI", "FRAX", "sUSD", "LUSD"],
  250: ["USDC"],
  1088: ["Metis", "Metis.USDT"],
  8453: ["USDbC", "SGETH"],
  59144: ["SGETH"],
  2222: ["USDT"],
  5000: ["USDC", "USDT", "mETH"],
};
