export default {
  1: {
    deposit: {
      "sy-steth": ["stETH", "ETH"],
      "sy-ezeth": ["ETH", "ezETH"],
      "sy-rseth": ["rsETH", "ETH", "stETH", "ETHx", "sfrxETH"],
      "sy-usde": ["USDe"],
      "sy-susde": ["USDe", "sUSDe"],
      "sy-zs-ezeth": ["ezETH", "ETH"],
      "sy-sweth": ["swETH", "ETH"],
      "sy-silo-crvusd": ["crvUSD"],
      "sy-sfrxeth": ["frxETH", "sfrxETH", "ETH"],
      "sy-weeth": ["weETH", "eETH", "ETH"],
      "sy-fraxusdc": ["USDC", "FRAX"],
      "sy-looks": ["LOOKS"],
      "sy-sape": ["APE"],
      "sy-reth-weth": ["ETH", "WETH", "rETH"],
      "sy-ankreth-weth": ["WETH", "ankrETH", "ETH"],
      "sy-stafireth-weth": ["rETH", "WETH", "ETH"],
      "sy-sweth-bbaweth": ["ETH", "WETH", "waWETH", "swETH"],
      "sy-stargate-usdt": ["USDT"],
      "sy-ankreth-wsteth": ["ETH", "wstETH", "ankrETH"],
      "sy-ethx-bbaweth": ["ETH", "WETH", "ETHx"],
      "sy-fusdc": ["fUSDC", "USDC"],
      "sy-oeth": ["OETH", "WOETH"],
      "sy-eusd": ["eUSD"],
      "sy-ethx": ["ETHx", "ETH"],
      "sy-sfrax": ["FRAX", "sFRAX"],
      "sy-ependle": ["PENDLE", "ePendle"],
    },
    lock: ["PENDLE"],
  },
  42161: {
    deposit: {
      "sy-glp": [
        "WBTC",
        "WETH",
        "USDC.e",
        "LINK",
        "UNI",
        "USDT",
        "MIM",
        "FRAX",
        "DAI",
        "USDC",
        "sGLP",
        "ETH",
      ],
      "sy-gdai": ["DAI", "gDAI"],
      "sy-stargate-usdt": ["USDT"],
      "sy-camelot-pendle-eth": ["PENDLE", "WETH"],
      "sy-camelot-arb-eth": ["WETH", "ARB"],
      "sy-camelot-grail-arb": ["GRAIL", "ARB"],
      "sy-wsteth": ["wstETH"],
      "sy-reth": ["rETH"],
      "sy-hlp": ["HLP"],
      "sy-mpendle": ["PENDLE", "mPendle"],
      "sy-kyber": ["wstETH", "axl-wstETH"],
      "sy-muxlp": ["sMLP"],
    },
    lock: ["PENDLE"],
  },
  10: {
    deposit: {
      "sy-wsteth": ["wstETH"],
      "sy-reth": ["rETH"],
    },
    lock: ["PENDLE"],
  },
  56: {
    deposit: {
      "sy-wbeth": ["wBETH", "ETH"],
      "sy-thena-frxeth-eth": ["ETH", "frxETH"],
      "sy-ankrbnb": ["ankrBNB", "BNB"],
    },
    lock: ["PENDLE"],
  },
};
