export default {
  1: {
    steth: ["stETH", "ETH"],
    ezeth: ["ETH", "ezETH"],
    rseth: ["rsETH", "ETH", "stETH", "ETHx", "sfrxETH"],
    usde: ["USDe"],
    susde: ["USDe", "sUSDe"],
    "zs-ezeth": ["ezETH", "ETH", "zs-ezETH"],
    sweth: ["swETH", "ETH"],
    "silo-crvusd": ["crvUSD"],
    sfrxeth: ["frxETH", "sfrxETH", "ETH"],
    weeth: ["weETH", "eETH", "ETH"],
    fraxusdc: ["USDC", "FRAX"],
    looks: ["LOOKS"],
    sape: ["APE"],
    "reth-weth": ["ETH", "WETH", "rETH"],
    "ankreth-weth": ["WETH", "ankrETH", "ETH"],
    "stafireth-weth": ["rETH", "WETH", "ETH"],
    "sweth-bbaweth": ["ETH", "WETH", "waWETH", "swETH"],
    "stargate-usdt": ["USDT"],
    "ankreth-wsteth": ["ETH", "wstETH", "ankrETH"],
    "ethx-bbaweth": ["ETH", "WETH", "ETHx"],
    fusdc: ["fUSDC", "USDC"],
    oeth: ["OETH", "WOETH"],
    eusd: ["eUSD"],
    ethx: ["ETHx", "ETH"],
    sfrax: ["FRAX", "sFRAX"],
    ependle: ["PENDLE", "ePendle"],
  },
  42161: {
    glp: [
      "WBTC",
      "WETH",
      "USDC.e",
      "LINK",
      "UNI",
      "USDT",
      "MIM",
      "FRAX",
      "DAI",
      "USDC",
      "sGLP",
      "ETH",
    ],
    gdai: ["DAI", "gDAI"],
    "stargate-usdt": ["USDT"],
    "camelot-pendle-eth": ["PENDLE", "WETH"],
    "camelot-arb-eth": ["WETH", "ARB"],
    "camelot-grail-arb": ["GRAIL", "ARB"],
    wsteth: ["wstETH"],
    reth: ["rETH"],
    hlp: ["HLP"],
    mpendle: ["PENDLE", "mPendle"],
    kyber: ["wstETH", "axl-wstETH"],
    muxlp: ["sMLP"],
  },
  10: {
    wsteth: ["wstETH"],
    reth: ["rETH"],
  },
  56: {
    wbeth: ["wBETH", "ETH"],
    "thena-frxeth-eth": ["ETH", "frxETH"],
    ankrbnb: ["ankrBNB", "BNB"],
  },
};
