const arbSupportedTokens = [
  "BTC",
  "WBTC",
  "ETH",
  "WETH",
  "LTC",
  "XRP",
  "ATOM",
  "NEAR",
  "ARB",
  "SOL",
  "UNI",
  "LINK",
  "AAVE",
  "AVAX",
  "BNB",
  "OP",
  "GMX",
  "WBNB",
  "USDC.e",
  "USDT",
  "DAI",
];

const avaxSupportedTokens = [
  "AVAX",
  "WAVAX",
  "BTC",
  "ETH",
  "SOL",
  "USDT",
  "USDC",
  "USDC.e",
  "USDT.e",
  "DAI.e",
];

export default {
  42161: {
    deposit: {
      "btc-usdc": ["WBTC", "USDC"],
      "wbtc-usdc": ["WBTC", "USDC"],
      "eth-usdc": ["WETH", "USDC", "ETH"],
      "weth-usdc": ["WETH", "USDC", "ETH"],
      "doge-usdc": ["USDC"],
      "ltc-usdc": ["USDC"],
      "xrp-usdc": ["USDC"],
      "atom-usdc": ["USDC"],
      "near-usdc": ["USDC"],
      "arb-usdc": ["USDC"],
      "sol-usdc": ["USDC"],
      "uni-usdc": ["UNI", "USDC"],
      "link-usdc": ["LINK", "USDC"],
      "aave-usdc": ["USDC"],
      "avax-usdc": ["USDC"],
      "bnb-usdc": ["USDC"],
      "op-usdc": ["OP", "USDC"],
      "gmx-usdc": ["GMX", "USDC"],
      "wbnb-usdc": ["USDC"],
      "usdc-usdc.e": ["USDC", "USDC.e"],
      "usdc-usdt": ["USDC, USDT"],
      "usdc-dai": ["USDC", "DAI"],
    },
    long: arbSupportedTokens,
    short: arbSupportedTokens,
    stake: ["GMX"],
  },
  43114: {
    deposit: {
      "avax-usdc": ["WAVAX", "USDC"],
      "btc-usdc": ["WBTC", "USDC"],
      "wbtc-usdc": ["WBTC", "USDC"],
      "eth-usdc": ["WETH", "USDC"],
      "weth-usdc": ["WETH", "USDC"],
      "sol-usdc": ["USDC"],
      "usdc-usdc.e": ["USDC", "USDC.e"],
      "usdt-usdt.e": ["USDT"],
      "usdc-usdt.e": ["USDC"],
      "usdc-dai.e": ["USDC"],
      "doge-usdc": ["USDC"],
      "ltc-usdc": ["USDC"],
      "xrp-usdc": ["USDC"],
    },
    long: avaxSupportedTokens,
    short: avaxSupportedTokens,
    stake: ["GMX"],
  },
};
