export default {
  42161: {
    "btc-usdc": ["WBTC", "USDC"],
    "wbtc-usdc": ["WBTC", "USDC"],
    "eth-usdc": ["WETH", "USDC", "ETH"],
    "weth-usdc": ["WETH", "USDC", "ETH"],
    "doge-usdc": ["USDC"],
    "ltc-usdc": ["USDC"],
    "xrp-usdc": ["USDC"],
    "atom-usdc": ["USDC"],
    "near-usdc": ["USDC"],
    "arb-usdc": ["USDC"],
    "sol-usdc": ["USDC"],
    "uni-usdc": ["UNI", "USDC"],
    "link-usdc": ["LINK", "USDC"],
    "aave-usdc": ["USDC"],
    "avax-usdc": ["USDC"],
    "bnb-usdc": ["USDC"],
    "op-usdc": ["OP", "USDC"],
    "gmx-usdc": ["GMX", "USDC"],
    "wbnb-usdc": ["USDC"],
    "usdc-usdc.e": ["USDC", "USDC.e"],
    "usdc-usdt": ["USDC, USDT"],
    "usdc-dai": ["USDC", "DAI"],
  },
  43114: {
    "avax-usdc": ["WAVAX", "USDC"],
    "btc-usdc": ["WBTC", "USDC"],
    "wbtc-usdc": ["WBTC", "USDC"],
    "eth-usdc": ["WETH", "USDC"],
    "weth-usdc": ["WETH", "USDC"],
    "sol-usdc": ["USDC"],
    "usdc-usdc.e": ["USDC", "USDC.e"],
    "usdt-usdt.e": ["USDT"],
    "usdc-usdt.e": ["USDC"],
    "usdc-dai.e": ["USDC"],
    "doge-usdc": ["USDC"],
    "ltc-usdc": ["USDC"],
    "xrp-usdc": ["USDC"],
  },
};
